[package]
name = "fs-format"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tianmu-fs = { path = "../tianmu-fs" }
tisu-fs = { path = "../tisu-fs" }
tisu-driver = { path = "../tisu-driver" }
# tianmu-fs = { git = "https://github.com/TisuOS/tianmu-fs" }
# tisu-fs = { git = "https://github.com/TisuOS/tisu-fs" }
# device-buffer = { git = "https://github.com/TisuOS/device-buffer" }
